
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 933606
	#The name of the modpack
	modpackName = "TerraFirmaSetsu"
	#The version of the modpack
	modpackVersion = "8.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

