
[General]
	#Only butchery knives cause corpses/carcasses to drop. Disable to allow any tool/weapon to cause them to drop.
	"Specific Tools Only" = false
	#Enable/Disable first join message.
	"First Join Message" = false
	#Enable/Disable End Dragon armor
	"Dragon Armor" = true
	#Enalbe/Disable guide book on first join
	"Guide Book" = true
	#Enable this to use vanilla foods instead of butchery's foods
	"Vanilla Drops" = false
	#Enable/Disable blood spreading
	"Blood Spread" = true
	#Enable/Disable carcass weight effects
	"Carcass Weight" = true
	#Enable/Disable blocks weight effects
	"Block Weight" = false
	#Enable/Disable pillager disguise blending affect
	"Pillager Disguise" = true
	#Collect salt water from ocean biomes using a bucket
	"Salt Water" = true
	#Instantly drain carcasses/corpses
	"Instant Drain" = false
	#Enable/Disable sulfur ore generation
	"Sulfur Ore" = false
	#Enable/Disable salt generation
	Salt = false
	#Enable to use a vanilla bucket to collect salt water. Disable to use butchery's own bucket.
	"Salt Water: Vanilla Bucket" = true
	#Enable/Disable overlay hints
	"Hints (Disabled due to bugs)" = false
	#Enable/Disable organ drops
	Organs = true

["Block Audio"]
	#Enable/Disable the grinders sound effect when in use.
	"Grinder Sound Effect" = true
	#Enable/Disable the crushers sound effect when in use.
	"Crusher Sound Effect" = true

[Structures]
	#Enable/Disable the butchers house structure
	butchers_house = true
	#Enable/Disable the salt formation structure
	salt_formation = true

["Boss Carcasses"]
	#Enable/Disable End Dragon carcass
	"End Dragon" = true
	#Enable/Disable Elder Guardian carcass
	"Elder Guardian" = true
	#Enable/Disable Wither carcass
	Wither = true

["Mod Compatiblities"]
	#Enable/Disable farmers delight foods as drops
	"Farmer's Delight" = false
	#Enable to make TFC mobs drop carcasses
	"Terra Firma Craft Carcasses" = false
	#Enable to use TFC drops instead of Butchery drops
	"Terra Firma Craft drops" = false
	#Enable to obtain life essence buckets from blood drain when right clicked with empty bucket
	"Blood Magic" = true
	#Enable vampirism drops from corpses
	Vampirism = false
	#Enable vampirism delight drops from corpses
	"Vamp Delight" = false
	#Enable werewolves drops from corpses
	Werewolves = false
	#Enable/Disable Hexerei drops
	Hexerei = false

["Carcasses/Corpses"]
	Player = false
	Bat = false
	Chicken = false
	Cow = false
	Frog = false
	Goat = false
	Hoglin = false
	Pig = false
	Rabbit = false
	Sheep = false
	Squid = false
	Turtle = false
	Villager = false
	Fox = false
	"Puffer Fish" = false
	Llama = false
	Panda = false
	"Polar Bear" = false
	Salmon = false
	Dolphin = false
	Cod = false
	Camel = false
	"Glow Squid" = false
	Skeleton = false
	Zombie = false
	Witch = false
	Creeper = false
	Pillager = false
	Spider = false
	"Cave Spider" = false
	Enderman = false
	Husk = false
	Drowned = false
	"Wither Skeleton" = false
	Piglin = false
	"Zombified Piglin" = false
	Slime = false
	Horse = false
	Wolf = false
	Axolotl = false
	Donkey = false
	Mule = false
	Ocelot = false
	Sniffer = false
	Strider = false
	Evoker = false
	Guardian = false
	Phantom = false
	"Piglin Brute" = false
	Shulker = false
	Silverfish = false
	Zoglin = false
	"Zombie Villager" = false
	Cat = false

[Seasonal]
	#Enable/Disable the Halloween update
	Halloween = false
	#Enable/Disable the Christmas update
	Christmas = false

