
[General]
	#Show GUI hints when looking at carcasses.
	"Show Hints" = true
	#Enable to have carcasses drop with ONLY cleavers. Disable to have carcasses drop no matter what kills the mob.
	"Only Cleavers Drop Carcasses" = false
	#Instantly bleed carcasses.
	"Instant Bleeding" = false
	#Enable organ drops
	Organs = true
	#Enable carcass weight (slowness effect when carcasses are in your inventory)
	"Weighted Carcasses" = true
	#Enable looting when butchering carcasses
	"Looting Enchantment" = true
	#Enable sulfur ore generation
	"Sulfur Ore Generation" = true
	#Enable salt generation
	"Salt Generation" = true
	#Enable blood spread
	"Blood Spread" = true

[Mobs]
	#Enable Axolotl Carcass
	Axolotl = false
	#Enable Bat Carcasses
	"Bat Carcass" = false
	#Enable Bee Carcasses
	"Bee Carcass" = false
	#Enable Brown Mooshroom Carcasses
	"Brown Mooshroom" = false
	#Enable Camel Carcasses
	Camel = false
	#Enable Cat Carcasses
	Cat = false
	#Enable Cave Spider Carcasses
	"Cave Spider" = false
	#Enable Chicken Carcasses
	"Chicken Carcass" = false
	#Enable Cod Carcasses
	Cod = false
	#Enable Cow Carcasses
	"Cow Carcass" = false
	#Enable Creeper Carcasses
	Creeper = false
	#Enable Dolphin Carcasses
	"Dolphin Carcass" = false
	#Enable Donkey Carcasses
	Donkey = false
	#Enable Drowned Corpses
	Drowned = false
	#Enable Elder Guardian Carcass
	"Elder Guardian" = false
	#Enable Evoker Corpses
	Evoker = false
	#Enable Ender Dragon Carcass
	"Ender Dragon" = false
	#Enable Enderman Corpses
	Enderman = false
	#Enable Endermite Carcass
	Endermite = false
	#Enable Fox Carcasses
	Fox = false
	#Enable Frog Carcass
	Frog = false
	#Enable Glow Squid Carcasses
	"Glow Squid Carcass" = false
	#Enable Goat Carcasses
	"Goat Carcass" = false
	#Enable Guardian Carcasses
	Guardian = false
	#Enable Hoglin Carcasses
	Hoglin = false
	#Enable Horse Carcasses
	Horse = false
	#Enable Husk Corpses
	Husk = false
	#Enable Iron Golem Corpses
	"Iron Golem" = false
	#Enable Llama Carcass
	Llama = false
	#Enable Magma Cube Carcass
	"Magma Cube" = false
	#Enable Mule Carcasses
	Mule = false
	#Enable Ocelot Carcasses
	Ocelot = false
	#Enable Panda Carcasses
	Panda = false
	#Enable Pig Carcasses
	"Pig Carcass" = false
	#Enable Piglin Corpses
	Piglin = false
	#Enable Piglin Brute Corpses
	"Piglin Brute" = false
	#Enable Pillager Corpses
	Pillager = false
	#Enable Polar Bear Carcass
	"Polar Bear" = false
	#Enable Pufferfish Carcass
	Pufferfish = false
	#Enable Phantom Carcass
	Phantom = false
	#Enable Rabbit Carcass
	Rabbit = false
	#Enable Red Mooshroom Carcasses
	"Red Mooshroom" = false
	#Enable Salmon Carcasses
	Salmon = false
	#Enable Sheep Carcasses
	"Sheep Carcass" = false
	#Enable Shulker Carcass
	Shulker = false
	#Enable Silverfish Carcass
	Silverfish = false
	#Enable Skeleton Carcass
	Skeleton = false
	#Enable Skeleton Horse Carcass
	"Skeleton Horse" = false
	#Enable Slime Carcass
	Slime = false
	#Enable Sniffer Carcass
	Sniffer = false
	#Enable Spider Carcasses
	"Spider Carcass" = false
	#Enable Squid Carcasses
	"Squid Carcass" = false
	#Enable Stray Carcass
	Stray = false
	#Enable Strider Carcass
	Strider = false
	#Enable Turtle Carcass
	Turtle = false
	#Enable Villager Corpses
	Villager = false
	#Enable Vindicator Corpses
	Vindicator = false
	#Enable Warden Corpses
	Warden = false
	#Enable Witch Corpses
	Witch = false
	#Enable Wither Skeleton Corpses
	"Wither Skeleton" = false
	#Enable Wither Corpses
	Wither = false
	#Enable Wolf Corpses
	Wolf = false
	#Enable Zoglin Corpses
	Zoglin = false
	#Enable Zombie Corpses
	Zombie = false
	#Enable Zombie Horse Corpses
	"Zombie Horse" = false
	#Enable Zombie Villager Corpses
	"Zombie Villager" = false
	#Enable Zombified Piglin Corpses
	"Zombified Piglin" = false

["Mod Compatibilities"]
	#Enable Farmers Delight Compatibility
	"Farmers Delight" = true

["Butchers Coin Reward"]
	#The loottable that the butchery coin rewards from.
	Loottable = "minecraft:chests/end_city_treasu"

